services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/code/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=shark_db
      - POSTGRES_USER=shark_user
      - POSTGRES_PASSWORD=shark_password
      - TESTING=False
      - SECRET_KEY=myfuckingsecretke123
      - REFRESH_SECRET_KEY=myrefreshsecret
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRES=5
      - REFRESH_TOKEN_EXPIRES=43829
    depends_on:
      - db
    restart: always
    networks:
      - shark
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=shark_db
      - POSTGRES_USER=shark_user
      - POSTGRES_PASSWORD=shark_password
    restart: always
    ports:
      - "5432:5432"
    networks:
      - shark

networks:
  shark:
