services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/code/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=shark_db
      - POSTGRES_USER=shark_user
      - POSTGRES_PASSWORD=shark_password
    depends_on:
      - db
    restart: always
    networks:
      - shark
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=shark_db
      - POSTGRES_USER=shark_user
      - POSTGRES_PASSWORD=shark_password
    restart: always
    networks:
      - shark

networks:
  shark:
